### ISSUE TITLE
No handler found for the command: 'workbench.action.files.closeFile'

### ISSUE THREAD

**Issue by jaytaylor** [Microsoft/vscode-sublime-keybindings#1]
After installing Sublime Keybindings `cmd-w` no longer closes the currently open file.  This error is displayed across the top instead of closing the file:

    No handler found for the command: 'workbench.action.files.closeFile'. Ensure there is an activation event defined, if you are an extension.

Screenshot:

![screen shot 2016-03-15 at 4 53 28 pm](https://cloud.githubusercontent.com/assets/435652/13797944/792cd548-eace-11e5-9f5a-88ac373679da.png)

Platform: OS-X 10.9.5

Screenshots of all installed plugins:

![screen shot 2016-03-15 at 4 53 59 pm](https://cloud.githubusercontent.com/assets/435652/13797954/a2e2db44-eace-11e5-8dc1-bc039c504dd0.png)

![screen shot 2016-03-15 at 4 54 05 pm](https://cloud.githubusercontent.com/assets/435652/13797958/a6ddd276-eace-11e5-8f6d-5a4fbc4c82c7.png)

After uninstalling Sublime Keybindings `cmd-w` works fine.

**Comment by waderyan** [comment]
Interesting.. I'll take a look. Likely a typo

**Comment by waderyan** [comment]
Yep. Looks like I mixed up the order. Fixed with ea86aaf23b02bf0c6f79a656c6aa665e24e6aab3. Give me a few and I'll re-publish
