### ISSUE TITLE
Missing Cmd-Shift-D behaviour

### ISSUE THREAD

**Issue by andig** [microsoft/vscode-sublime-keybindings#100]
On sublime, Cmd-Shift-D duplicates current selection. Current VS Code behaviour is insofar inconsistent in that it always duplicates the entire lines, not only the selection in case it does not span multiple lines.

Would greatly appreciate the original behaviour :)

**Comment by DrDonkey** [comment]
Not really. **Ctrl shift d** copies entire line for me in sublime 3 as well.

**Comment by andig** [comment]
> Not really. Ctrl shift d copies entire line for me in sublime 3 as well.

That's funny. When I select a word and `Cmd+Shift+D` on Mac it duplicates just the word. Looking at the keymap I can only find:

	{ "keys": ["super+shift+d"], "command": "duplicate_line" },

Stumped where the desired behaviour comes from, but I really like it ;)

**Comment by mtomov** [comment]
Would love to have this behaviour as well : )

The behaviour depends if a selection has been made or not.

A) on selection -> duplicates the selected text to the right
B) on no selection -> duplicates the entire line

**Comment by andig** [comment]
There is actually another thing missing that's quite annoying. When using `Cmd-Shift-D` in a multi-selection and then breaking that selection into individual lines (`Cmd-Shift-L`) then only the last cursor position will actually be edited as multiple lines. For the other positions only the first line of each position gets edited.

**Comment by andig** [comment]
No feedback :( any interest in having this in its own plugin?

**Comment by dufferzafar** [comment]
@andig I would love this functionality, and was a bit surprised to see that vscode didn't do this by default. I think you should create a separate plugin and if this gets merged here, then just remove your plugin?

**Comment by Djarnis** [comment]
This is one of the functions that I can't live without, hence stopping me from going all VS ...

**Comment by andig** [comment]
> This is one of the functions that I can't live without, hence stopping me from going all VS ...

I've just published https://marketplace.visualstudio.com/items?itemName=andig.sublime-cmd-shift-d. Let me know if anything's wrong in https://github.com/andig/vscode-sublime-cmd-shift-d/issues

**Comment by dufferzafar** [comment]
@andig: I tried it, works just fine. Thanks :smile:

**Comment by Djarnis** [comment]
It works! Thx! Now I think I will give VSCode another go ;)
