### ISSUE TITLE
Failed to import settings

### ISSUE THREAD

**Issue by EfimenkoAndrew** [microsoft/vscode-sublime-keybindings#108]
I got this message:
No Sublime settings file found at the default location: C:\Users\aea\AppData\Roaming\Sublime Text 3\Preferences.sublime-settings 
How can i solve it? I have no Sublime Text 3
How can I use this extension? How can I import settings? What should i do to make in work?

**Comment by chrisdias** [comment]
Hi - if you don't have Sublime Text 3 installed then you can safely ignore this.
