### ISSUE TITLE
代码补全功能失效

### ISSUE THREAD

**Issue by SquabbyZ** [microsoft/vscode-sublime-keybindings#110]
用 VScode 长时间打开一个中型项目（及以上）的时候，代码补全功能失效，必须要完全关闭编辑器才能再次有代码补全效果

**Comment by chrisdias** [comment]
using google translate:

> When using VScode to open a medium-sized project (and above) for a long time, the code completion function fails. You must close the editor completely to have the code completion effect again.

This seems like a VS Code issue, not a sublime key binding issue. if you can still reproduce this problem, please open an issue in https://github.com/microsoft/vscode/issues/new. thanks.
