### ISSUE TITLE
VS Code Remote: mark the extension as a UI extension

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-sublime-keybindings#113]
The extension is currently run as a workspace extension (since the extension contains code).
However, the extension should be a [UI extension](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types) pls see https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location.

**Comment by auchenberg** [comment]
Extension kind already updated in https://github.com/microsoft/vscode-sublime-keybindings/commit/fbc57245dad968960c127d17403ad7e91863d7e0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Publishing new version.
