### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by claquirou** [microsoft/vscode-sublime-keybindings#115]
- Issue Type: `Performance`
- Extension Name: `sublime-keybindings`
- Extension Version: `4.0.3`
- OS Version: `Linux x64 5.0.0-25-generic`
- VSCode version: `1.37.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/claquirou/ms-vscode.sublime-keybindings-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by chrisdias** [comment]
hi!  it doesn't look like you've attached the cpu profile, can you upload?
