### ISSUE TITLE
cmd+alt+f is behaving incorrectly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-sublime-keybindings#20]
Testing https://github.com/Microsoft/vscode/issues/14317

The following sublime keybinding:

``` json
{ "keys": ["super+alt+f"], "command": "show_panel", "args": {"panel": "replace", "reverse": false} },
```

Opens the find in active file dialog, with replace visible and the find keyword field focused. Currently under the extension it opens find and replace _in files_ with the _replace keyword_ field focused.

**Comment by ryansonshine** [comment]
Duplicates #38
