### ISSUE TITLE
Cmd + Left click does not do anything

### ISSUE THREAD

**Issue by ducdigital** [Microsoft/vscode-sublime-keybindings#27]
Doesn't seem like the` Cmd + Left click `work for mac. 

After installation of the plugin, the `alt + shift + left mouse` / `alt + left mouse` keybinding also stop working.

Not sure if it's my installation or the plugin, can anyone verify?

**Comment by waderyan** [comment]
What are you wanting `cmd+left click` to do? If you are wanting it to add multi cursors that is currently not supported by VS Code, but I could use your upvote on this issue https://github.com/Microsoft/vscode/issues/3776

I can't reproduce the `alt+shift+left mouse / alt+left mouse` issue. That is still adding multi cursors for me. I'm assuming you are on a Mac, correct?
