### ISSUE TITLE
[Feature request] End of line vertical selection

### ISSUE THREAD

**Issue by ducdigital** [Microsoft/vscode-sublime-keybindings#28]
![xzi4b](https://cloud.githubusercontent.com/assets/1712140/20185010/c62b6fea-a76a-11e6-8529-64b8e26d43b2.gif)

Can you guys add support to this too?

**Comment by waderyan** [comment]
Thank you for opening this issue. This is supported with `shift+cmd+l`. Are you expecting a different keybinding?
