### ISSUE TITLE
(⌘K, ⌘L) and (⌘K, ⌘U) shortcuts

### ISSUE THREAD

**Issue by matejkramny** [Microsoft/vscode-sublime-keybindings#29]
Hi, first of all. Thank you for making these keybindings, it's extremely useful as someone coming from sublime!

I'd like to contribute these shortcuts, they transform selected text selections.

- ⌘K, ⌘L transforms selection(s) to lowercase
- ⌘K, ⌘U transforms selection(s) to uppercase

I can't find the corresponding command for the editor. Would you mind helping me out?

Thanks!

**Comment by matejkramny** [comment]
Nevermind, found this: https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case.

The transformation shortcuts do exist in sublime though, if it is possible to implement them here it'd bring this package closer to subilme.

**Comment by waderyan** [comment]
Hi these are on our list to implement. Please upvote there https://github.com/Microsoft/vscode/issues/3776
