### ISSUE TITLE
Shortcuts don't respect keyboard layout

### ISSUE THREAD

**Issue by ericelliott** [Microsoft/vscode-sublime-keybindings#31]
I'm using the Dvorak keyboard layout.

The following shortcuts appear to be configured in the Default Keyboard Shortcuts, but don't work:

```
{ "key": "shift+cmd+=",           "command": "workbench.action.zoomIn" },
{ "key": "cmd+=",                 "command": "workbench.action.zoomIn" },
{ "key": "shift+cmd+-",           "command": "workbench.action.zoomOut" },
{ "key": "cmd+-",                 "command": "workbench.action.zoomOut" },
```

Instead, it appears to indent the current line in. When I use the physical + and - keys, it does work.

This doesn't work whether I use the physical key or the mapped key:

```
{ "key": "alt+cmd+/",             "command": "editor.action.commentLine",
                                     "when": "editorTextFocus" },
```

Note: when editing key bindings, I get little info hints that tell me to use the mapped keys (the ones that don't work) instead of the physical keys. Those info hints describe behavior that I want, but doesn't exist.

**Comment by waderyan** [comment]
@alexandrudima could I get your help here...

**Comment by auchenberg** [comment]
This issue was moved to Microsoft/vscode#35554
