### ISSUE TITLE
Replace "Bracket Selection" suggestion with my extension (or integrate it)

### ISSUE THREAD

**Issue by SuperV1234** [Microsoft/vscode-sublime-keybindings#32]
Hello, I was unsatisfied with the suggested ["Bracket Selection"](https://marketplace.visualstudio.com/items?itemName=guosong.bracketselection) because it only works on a per-line basis and doesn't work with nested scopes. It's behavior is totally different from Sublime Text.

I made my own extension: [**expand-selection-to-scope**](https://github.com/SuperV1234/vscode-expand-selection-to-scope).

Here's a gif:

![example gif](https://github.com/SuperV1234/vscode-expand-selection-to-scope/raw/master/example.gif)

The behavior is much similar to ST's feature and supports arbitrarily nested scopes. I would be happy to integrate this inside `vscode-sublime-keybindings`  or just to have it suggested on the README *(if you think it's better than the current suggestion)*. 

Cheers,
Vittorio

**Comment by waderyan** [comment]
Sounds good to me. Please make a PR for the README and I'll merge it in.
