### ISSUE TITLE
Add snippet suggestions to the top of the list

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-sublime-keybindings#36]
This was brought up in a thread on Twitter. We should consider adding this to the Sublime extension. 

![image](https://cloud.githubusercontent.com/assets/2449568/21622826/48a6ed28-d1b4-11e6-8005-035d0aea340c.png)

https://t.co/6sU44AxCHl

From @egamma 

> I wonder whether in the Sublime extension we should define the setting as follows to avoid this problem 

```
"editor.snippetSuggestions": "top"
```

**Comment by waderyan** [comment]
Done with 2.0 extension release

**Comment by auchenberg** [comment]
Closing as this is implemented. https://github.com/Microsoft/vscode-sublime-keybindings/blob/master/extension.js#L15
