### ISSUE TITLE
Rename the extension "Sublime Text Emulation" 

### ISSUE THREAD

**Issue by waderyan** [microsoft/vscode-sublime-keybindings#37]
We are planning on adding more functionality than simply keymaps, including mouse mappings, settings, etc. 

"Sublime Keymap" will not capture the extent of the extension, so renaming it to Sublime Emulation (like the VIM Emulation extension) is a good candidate. 

cc @egamma

**Comment by chrisdias** [comment]
The name has been in place for so long I don't think we need to change it now.
