### ISSUE TITLE
Ctrl + H should be mapped to editor.action.startFindReplaceAction

### ISSUE THREAD

**Issue by EFanZh** [Microsoft/vscode-sublime-keybindings#38]
OS: Windows
Version: 1.8.1

I think <kbd>Ctrl</kbd> + <kbd>H</kbd> should be mapped to `editor.action.startFindReplaceAction` command instead of  `workbench.action.replaceInFiles` command because <kbd>Ctrl</kbd> + <kbd>H</kbd> in Sublime Text Editor does replacing in the current file only.

Or just remove this binding to use the default binding.

**Comment by ryansonshine** [comment]
I started working on this then I saw I wasn't alone 👍

**Comment by EFanZh** [comment]
@waderyan I think it should be `editor.action.startFindReplaceAction`, not `workbench.action.startFindReplaceAction`.
