### ISSUE TITLE
plugin is now auto-adding workspace settings?

### ISSUE THREAD

**Issue by bmoyles** [Microsoft/vscode-sublime-keybindings#45]
This commit from a few days ago:
https://github.com/Microsoft/vscode-sublime-keybindings/commit/d23c54fe5a056e516a9af19189d3fcb185d564e1
seems to have resulted in the plugin dropping workspace-level settings in any project I open with no ability to tell the plugin to stop (or change what it's setting at the very least -- these defaults do not align with my global defaults).

Is that intentional or are there plans to allow users to affect this behavior in any way?

**Comment by fengcen** [comment]
Yes. This plugin shouldn't create workspace settings and enable minimap. It waste my time to figure out why it would automatically create workspace settings and I have to disable this plugin now!

**Comment by waderyan** [comment]
This has been rolled back now.
