### ISSUE TITLE
Upgrade from 1.9.0 turns on minimap in user settings

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-sublime-keybindings#48]
_From @rnemec on March 1, 2017 22:53_

- VSCode Version: 1.10.0
- OS Version: 10.11.6

Steps to Reproduce:

1. Upgraded
2. See minimap
3. Don't like minimap
4. Open settings - enabled = false by default
5. Wonder
6. Copy setting to user settings and set again to false
7. CANNOT GET RID of that minimap. SAM-I-AM - I do not like green eggs and ham.

_Copied from original issue: Microsoft/vscode#21665_

**Comment by egamma** [comment]
_From @rnemec on March 1, 2017 22:58_

Please, let me know what other information I can provide. I cannot believe that this bug is not yet logged - it must be something unusual in my setup...

**Comment by egamma** [comment]
_From @jordanmkasla2009 on March 2, 2017 0:49_

I can't reproduce this. What OS / Extensions / User Settings are you using?

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 0:52_

OS = Mac OS 10.11.6
and several extensions (although WHY would they break the mini-thing?) Is there an easy way to dump some useful info for you? I assume this must be something local here since nobody else is complaining...

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 0:58_

## Mystery solved!

After the upgrade, for some reason the **workspace settings** had minimap.enable set to "true". I didn't put that in there, but it got there somehow during the upgrade.
I apologize, I didn't look at the workspace settings because I usually only set the user settings, not workspace.

**Comment by egamma** [comment]
_From @cjsaylor on March 2, 2017 1:9_

@rnemec I had the same thing happen as well. Seems to be some sort of bug with the upgrade from 1.09 to 1.10.

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 1:10_

Reopening as upgrade bug.

**Comment by egamma** [comment]
_From @fengcen on March 2, 2017 2:42_

I found that this extension "Sublime Text Keymap" will automatically create `.vscode` folder and settings.json

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 2:55_

I don't have "Sublime Text Keymap" extension. And I already had the settings.json in the workspace's .vscode, just not used much.
Is it possible that the upgrade would just add the minimap.enabled=true if there is settings.json in workspace's .vscode?

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 2:58_

I just upgraded to 1.10.1 and guess what - the upgrade added the minimap.enabled=true to my workspace settings **again**.

**Comment by egamma** [comment]
_From @fengcen on March 2, 2017 3:7_

I only know that "Sublime Text Keymap" will automatically enable minimap and create workspace setting.

It works fine for me after I disable this extension.

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 3:18_

Qiu, you are correct!
Keymap plugins.
I am using "Atom Keymap" and whenever the workspace is reloaded, it turns on the minimap. When the plugin is disabled, it behaves OK.

**Comment by egamma** [comment]
_From @gluons on March 2, 2017 6:24_

For me, `.vscode` folder always be automatically created every time I open VSCode. That's really annoying.
I'm using `Atom Keymap` too.

**Comment by egamma** [comment]
_From @rnemec on March 2, 2017 6:30_

A workaround for all who cannot wait for the Atom Keymap plugin to get fixed (not sure about other plugins):
1. go to file `~/.vscode/extensions/ms-vscode.atom-keybindings-2.0.0/out/src/extension.js`
2. comment out the body of the activate method
3. enjoy

Plus or minus some version number, and possibly something similar may work for the other plugin.

**Comment by egamma** [comment]
_From @alexandrudima on March 2, 2017 8:43_

We are looking into publishing a fixed version of this extension.

**Comment by egamma** [comment]
_From @alexandrudima on March 2, 2017 9:2_

We published a new version of this extension that no longer writes to workspace settings.

**Comment by egamma** [comment]
Moving the issue to the sublime extension repository.

**Comment by fox1t** [comment]
Fixed with this commit https://github.com/Microsoft/vscode-sublime-keybindings/pull/47/commits/1f9a7f0625d1890d770fc4f914483f0a4482b740

**Comment by waderyan** [comment]
Minimap is now the default.
