### ISSUE TITLE
F5 doesn't work when focus is in editor when Sublime is installed

### ISSUE THREAD

**Issue by richlander** [Microsoft/vscode-sublime-keybindings#50]
See: https://github.com/OmniSharp/omnisharp-vscode/issues/1341

If this extension is not installed, F5 works when focus is in the text editor. When the extension is installed, F5 does not work.

**Comment by egamma** [comment]
@waderyan the issue is that on the mac this extension binds F5 and CTRL+F5 to the sort lines commands.

I would argue that the Debug (F5) and Run (CTRL+F5) are more important than the sort lines commands and these keybindings should not be rebound. 

```json
         {
                "mac": "f5",
                "win": "f9",
                "linux": "f9",
                "key": "f9",
                "command": "editor.action.sortLinesAscending",
                "when": "editorFocus"
            },
            {
                "mac": "ctrl+f5",
                "win": "ctrl+f9",
                "linux": "ctrl+f9",
                "key": "ctrl+f9",
                "command": "editor.action.sortLinesDescending",
                "when": "editorFocus"
            },
```

I would argue that F5 is a primary

**Comment by waderyan** [comment]
Makes perfect sense.

**Comment by waderyan** [comment]
Fixed
