### ISSUE TITLE
Possibility of choosing multi cursor modifier

### ISSUE THREAD

**Issue by padamczewski** [Microsoft/vscode-sublime-keybindings#53]
Since in latest Visual Studio Code [update](https://code.visualstudio.com/updates/v1_13#_add-multiple-cursors-with-ctrl-cmd-click) new setting for multi cursor modifier was introduced it's now possible to use `ctrl` or `cmd` just like in Sublime Text. However the default option is still `alt` key, which isn't so natural for someone switching from ST to VSCode.

My idea is to show user a message with possibility of changing the VSCode default.
![multi-cursor-modifier](https://user-images.githubusercontent.com/12883043/27012126-0b8b7a7c-4ec2-11e7-8567-319b7e8c1db4.png)
The message is shown when user hasn't specified `ctrlCmd` in the settings and until the question has been answered.

It could also become a part of adding more functionality and renaming the extension as mentioned in #37. 

The code is just demonstration of functionality, not finished solution.  #52

**Comment by waderyan** [comment]
Fixed. Will be available in next update.
