### ISSUE TITLE
Error tone when using 'move lines down' action on macOS

### ISSUE THREAD

**Issue by lunelson** [microsoft/vscode-sublime-keybindings#58]
Using the keybinding `cmd-ctrl-downArrow` to perform the action `editor.action.moveLinesDownAction` causes a macOS error tone. Running macOS Sierra 10.12.6 and VSCode 1.15.1. Anyone seen this?

**Comment by lunelson** [comment]
Judging from [this atom thread](https://github.com/atom/atom/issues/1669), it may be an electron issue

**Comment by auchenberg** [comment]
https://github.com/electron/electron/issues/2617
