### ISSUE TITLE
Make quick open - enter behave like in Sublime

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-sublime-keybindings#60]
Suggest to add this binding for quick open in the sublime keybindins
https://github.com/Microsoft/vscode/issues/26977#issuecomment-338205000

See also this twitter thread
https://twitter.com/scottzirkel/status/923968461482622976

FYI @bpasero

**Comment by bpasero** [comment]
@egamma @auchenberg thanks for picking this up, I was planning to do a PR. We should also do this for the Atom keymap extension, who would be in charge?

**Comment by bpasero** [comment]
@auchenberg created https://github.com/Microsoft/vscode-sublime-keybindings/pull/63. I noticed in your previous commit on this that you only bound `Cmd+P`, but this should be bound on all platforms via `Ctrl+P` too imho.
