### ISSUE TITLE
Duplicate key binding

### ISSUE THREAD

**Issue by jrudio** [Microsoft/vscode-sublime-keybindings#7]
Cool extension! I was testing out the key binding and came across a [duplicate key binding.](https://github.com/Microsoft/vscode-sublime-keybindings/blob/master/package.json#L170-L177) When attempting to move a line up it moves down.

**Comment by waderyan** [comment]
Thank you. Fixed with 79834bf5d39c3cce3e09e0d2ce9992baa97ffb4b

Will publish soon.
