### ISSUE TITLE
Vintage mode

### ISSUE THREAD

**Issue by jbonigomes** [Microsoft/vscode-sublime-keybindings#72]
Sublime has a vintage mode, where VIM keybindings work alongside the standard Sublime shortcuts, is there a way to enable it in VSCode?

**Comment by auchenberg** [comment]
At this point we time you can have a the Sublime and [VIM keymap](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) installed, but there most likely will be conflicts which you'll have to resolve yourself in your settings.

**Comment by jbonigomes** [comment]
Thanks, @auchenberg how can I install them both at the same time?

**Comment by auchenberg** [comment]
@jbonigomes Go to settings -> Key map extensions => Install the ones you need, and say no to the warning prompt. Should be straightforward.

**Comment by jbonigomes** [comment]
thanks @auchenberg how do I know/find the conflicts?

**Comment by egamma** [comment]
@jbonigomes there is a command in the context menu of the keybindings editor.

![image](https://user-images.githubusercontent.com/172399/34886420-3ee77ace-f7c3-11e7-854c-a1c5aaa88e55.png)

**Comment by jbonigomes** [comment]
Thanks @egamma
