### ISSUE TITLE
Cycle to previous suggestions in VSCode

### ISSUE THREAD

**Issue by Naramsim** [Microsoft/vscode-sublime-keybindings#79]
[![enter image description here][1]][1]

Hi, is there a way in Visual Studio Code to cycle to suggested keywords even when you already selected one of them (by clicking TAB multiple times)? This is possible in Sublime. In VSCode, with the keybindings of Sublime it does not work.

In the GIF above, in order to cycle through keywords, I pressed TAB several times, after typing 'hel' and 'he'

  [1]: https://i.stack.imgur.com/hSCWY.gif

https://stackoverflow.com/questions/48883721/cycle-to-previous-suggestions-in-vscode

**Comment by egamma** [comment]
// fyi @jrieken

**Comment by jrieken** [comment]
see https://github.com/Microsoft/vscode/issues/28215
