### ISSUE TITLE
Command not found in all keybindings

### ISSUE THREAD

**Issue by axacheng** [Microsoft/vscode-sublime-keybindings#8]
Hi,

Unfortunately, i didnt get smooth experience with sublime keybinding after I first time installed vscode. I dont even know how to debug it. Please try to help. 

Thanks

![image](https://cloud.githubusercontent.com/assets/5593412/18162020/f1d82240-7066-11e6-9077-271f8ec5e67d.png)

![image](https://cloud.githubusercontent.com/assets/5593412/18162041/0ab01084-7067-11e6-825c-c5d2ebc54cfd.png)

**Comment by axacheng** [comment]
found in : [Stacks & Tabs: Added or changed commands](https://github.com/Microsoft/vscode/issues/6605)

**Comment by waderyan** [comment]
Fixed with PR #12
